const stringResource = {
    productName: 'cATF',
    leftNavPanel: {
        loginTitle: 'Login',
        loginTarget: 'login',
        loginIcon: 'fa-bar-chart-o',
        loginSubMenu: [],
        dashboardTitle: 'Dashboard',
        dashboardTarget: 'dashboard',
        dashboardIcon: 'fa-bar-chart-o',
        dashboardSubMenu: [],
        configDevicesTitle: 'Config Devices',
        configDevicesTarget: 'configDevices',
        configDevicesIcon: 'fa-tachometer',
        configDevicesSubMenu: [],
        configTrafficTitle: 'config Traffic',
        configTrafficTarget: 'configTraffic',
        configTrafficIcon: 'fa-table',
        configTrafficSubMenu: [],
    },
    dashboardPanel: {
        connectionTitle: 'Device List',
        connectIcon: 'fa-comments',
        connectSubText: 'Connected Devices',
        connectLeftAction: 'Device List',
        connectCardColor: '#337ab7',

        startTrafficTitle: 'startTraffics',
        startTrafficIcon: 'fa-tasks',
        startTrafficSubText: 'Groups ready to run traffic',
        startTrafficLeftAction: 'Start Traffic',
        startTrafficCardColor: '#5cb85c',

        viewReportsTitle: 'viewReport',
        viewReportsIcon: 'fa fa-support',
        viewReportsSubText: 'View Reports',
        viewReportsLeftAction: 'View Reports',
        viewReportsCardColor: '#9467bd',

        liveReportTitle: 'liveReport',
        liveReportIcon: 'fa fa-code',
        liveReportSubText: 'Live statistics',
        liveReportLeftAction: 'Live Statistics',
        liveReportCardColor: '#f0ad4e',

        dashboardPanelName: 'Dashboard',
        dashboardLiveStatus: 'Live Status',
        dashboardLiveClearButton: 'Clear',
        dashboardGridView: 'Grid',
        dashboardTableView: 'Table',
        dashboardMapView: 'Location',
        dashboardRebuildButton: 'Rebuild Device List'
    },
    configDevice: {
        configDevicePanelName: 'Config Devices',
        configDeviceThDeviceId: 'deviceId',
        configDeviceThDeviceName: 'deviceName',
        configDeviceThDeviceType: 'deviceType',
        configDeviceThGroupId: 'groupId',
        configDeviceThConnectionControl: 'connectionControl',
        configDeviceThVersion: 'version',
        configDeviceThIpAddress: 'ipAddress',
        configDeviceThSsid: 'ssid',
        configDeviceThConnectionStatus: 'connectionStatus',
    },
    configTraffic: {
        configTrafficPanelName: 'Config Traffic',
        configExternalTraffic: 'External Traffic',
        configInternalTraffic: 'Internal Traffic',
        configSelectTraffic: 'Select Traffic',
        configP2PTraffic: 'P2P Traffic',
        configTrafficAddButton: 'Add',
        url: 'URL',
        trafficDuration: 'Traffic Duration',
        userName: 'User Name',
        password: 'Password',
        timeoutDuration: 'Timeout Duration',
        fileName: 'File Name',
        portNumber: 'Port',
        destinationIp: 'Destination IP / URL',
        packetSize: 'Packet Size',
        portIpAddress: 'IP Address',
        options: 'Options',
        destinationIPAddress: 'Destination IP Address',
        serverGroupId: 'Server Group Id',
        calleeGroup: 'Callee Group',
        extraTrafficDuration: 'Extra Traffic Duration',
        iperfServer: 'IperfServer',
        iperfClient: 'IperfClient',
        ping: 'Ping',
        fTPUpload: 'FTP Upload',
        fTPDownload: 'FTP Download',
        youtube: 'Youtube',
        browsing: 'Browsing',
        atf_multiBrowsing: 'Multi URL Browsing',
        atf_captivePortal: 'Captive portal',
        traffic: 'Traffic',
        atf_internal_ftp: 'atf_internal_ftp',
        atf_video_streaming: 'Video Streaming',
        vlc_multicast: 'VLC Multicast',
        atf_internal_tcp: 'TCP',
        atf_ftpint_ul: 'U/L',
        atf_ftpint_dl: 'D/L',
        direction: 'Direction',
        atf_voip: 'VOIP',
        video: 'Video',
        optional: 'Optional'
    },
    headerPanel: {
        reboot: 'Reboot',
        shutDown: 'ShutDown',
        changePassword: 'Change Password',
        changeTimeZone: 'Change Time Zone',
        logout: 'Sign Out'
    },
};
export default stringResource